# NovaOS — Calamares Users Module
---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - adm
    - cdrom
    - sudo
    - dip
    - plugdev
    - lpadmin
    - audio
    - video
    - netdev

autologinGroup: autologin

sudoersGroup: sudo

# Password requirements
passwordRequirements:
    minLength: 1
    maxLength: -1
    libpwquality: []

# Allow weak passwords (user choice)
allowWeakPasswords: true
allowWeakPasswordsDefault: false

# Default shell
userShell: /bin/bash

# Set hostname from username
setHostname: EtcFile
writeHostsFile: true
