# NovaOS — Calamares Welcome Module
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
showDonateUrl: false

# Minimum requirements for installation
requirements:
    requiredStorage:    8.0    # GB minimum disk space
    requiredRam:        0.5    # GB minimum RAM (500 MB)
    internetCheckUrl:   http://google.com
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
